version: '3.9'
services:
  postgres:
    image: postgres:17.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=spring-admin
      - POSTGRES_DB=gout-tour